# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_faq', '0014_auto_20160821_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqconfig',
            name='namespace',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='Instance namespace'),
        ),
        migrations.AlterField(
            model_name='faqconfig',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='latestquestionsplugin',
            name='cache_duration',
            field=models.PositiveSmallIntegerField(default=0, help_text="The maximum duration (in seconds) that this plugin's content should be cached.", verbose_name='cache duration'),
        ),
        migrations.AlterField(
            model_name='latestquestionsplugin',
            name='questions',
            field=models.IntegerField(default=5, help_text='The number of questions to be displayed.', verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='mostreadquestionsplugin',
            name='cache_duration',
            field=models.PositiveSmallIntegerField(default=0, help_text="The maximum duration (in seconds) that this plugin's content should be cached.", verbose_name='cache duration'),
        ),
        migrations.AlterField(
            model_name='mostreadquestionsplugin',
            name='questions',
            field=models.IntegerField(default=5, help_text='The number of questions to be displayed.', verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='aldryn_faq.Category', verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='is top'),
        ),
        migrations.AlterField(
            model_name='question',
            name='number_of_visits',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='number of visits'),
        ),
        migrations.AlterField(
            model_name='questionlistplugin',
            name='questions',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='aldryn_faq.Question', verbose_name='questions'),
        ),
        migrations.AlterField(
            model_name='topquestionsplugin',
            name='cache_duration',
            field=models.PositiveSmallIntegerField(default=0, help_text="The maximum duration (in seconds) that this plugin's content should be cached.", verbose_name='cache duration'),
        ),
        migrations.AlterField(
            model_name='topquestionsplugin',
            name='questions',
            field=models.IntegerField(default=5, help_text='The number of questions to be displayed.', verbose_name='count'),
        ),
    ]
